apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ldo7la4m4-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:d7c8248b06b865665d42e8b1bb9a3199adb4d75d@sha256:43db719012041352ea70616fe84007a36be5b3a89792a68d1650bf380849f8dd
          name: container-image
